name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install CVC4
      run: sudo apt-get install -y cvc4
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --test spec_tests --verbose
